version: "3.8"
name: sklearn_provider_container

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      rabbit_mq:
        condition: service_healthy

  rabbit_mq:
    image: rabbitmq:3.11.13-management
    container_name: rabbit_mq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5

networks:
  default:
    name: sklearn_provider_network